# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeKit < Formula
  desc "CLI tool for bootstrapping Claude Code projects with best-practice templates"
  homepage "https://github.com/adrien-barret/claude-kit"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.4/claude-kit-v0.2.4-darwin-amd64.zip"
      sha256 "545883aa87ad5baf98a61c0185ae09716cb455e2fa6a9105d6f2ad62e2baaf6a"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.4/claude-kit-v0.2.4-darwin-arm64.zip"
      sha256 "939e521c5220ff41c4d4dae836c03cc8c459a7931011a8fb3597cfb1c71b10de"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.4/claude-kit-v0.2.4-linux-amd64.zip"
      sha256 "426f9a7ecabaddc5eb7686816974db76f605c20f1a309799a72043ded3d4cd5c"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.4/claude-kit-v0.2.4-linux-arm64.zip"
      sha256 "6c216fbabe37b93f48f9044459bf42d537538fb33515f33a2a13a4e5f5a4e033"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  test do
    system "#{bin}/ck", "version"
  end
end
