# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeKit < Formula
  desc "CLI tool for bootstrapping Claude Code projects with best-practice templates"
  homepage "https://github.com/adrien-barret/claude-kit"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.2/claude-kit-v0.2.2-darwin-amd64.zip"
      sha256 "9560cac7bccc166637e076610b6323c4f5a104ef0d6efc0e0d9dd1b1d16e217d"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.2/claude-kit-v0.2.2-darwin-arm64.zip"
      sha256 "5b903ee1db3f100289c00add7f782371f0ad141b25359d81848c1bb10b98d256"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.2/claude-kit-v0.2.2-linux-amd64.zip"
      sha256 "9e98924714e8f06797241039e37f7e3c7f68122558e7ee87ce70d3a165d18823"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.2/claude-kit-v0.2.2-linux-arm64.zip"
      sha256 "bcc474f3bb8804550ff15fd5b47a5bdb22396a42a518598a892c9f0165262170"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  test do
    system "#{bin}/ck", "version"
  end
end
