package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// CollabEntry represents a collaboration link between two agents.
type CollabEntry struct {
	Agent     string
	Direction string // "provides_to" or "depends_on"
	Artifacts []string
}

// BuildCollaborationMaps detects produce/consume overlaps between agents
// and returns a map of agent name to their collaboration entries.
func BuildCollaborationMaps(agents []AgentEntry) map[string][]CollabEntry {
	result := make(map[string][]CollabEntry)

	for i, a := range agents {
		for j, b := range agents {
			if i == j {
				continue
			}

			// A produces what B consumes → A provides_to B
			shared := overlap(a.Interfaces.Produces, b.Interfaces.Consumes)
			if len(shared) > 0 {
				result[a.Name] = append(result[a.Name], CollabEntry{
					Agent:     b.Name,
					Direction: "provides_to",
					Artifacts: shared,
				})
			}

			// A consumes what B produces → A depends_on B
			deps := overlap(a.Interfaces.Consumes, b.Interfaces.Produces)
			if len(deps) > 0 {
				result[a.Name] = append(result[a.Name], CollabEntry{
					Agent:     b.Name,
					Direction: "depends_on",
					Artifacts: deps,
				})
			}
		}
	}

	// Sort entries for deterministic output
	for name, entries := range result {
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].Agent != entries[j].Agent {
				return entries[i].Agent < entries[j].Agent
			}
			return entries[i].Direction < entries[j].Direction
		})
		result[name] = entries
	}

	return result
}

// overlap returns the set of strings present in both a and b.
func overlap(a, b []string) []string {
	set := make(map[string]struct{}, len(b))
	for _, s := range b {
		set[s] = struct{}{}
	}

	var shared []string
	for _, s := range a {
		if _, ok := set[s]; ok {
			shared = append(shared, s)
		}
	}
	return shared
}

// InjectCollaborationMaps writes the collaboration map section into each
// agent's .md file. It replaces an existing section or appends a new one.
func InjectCollaborationMaps(agentsDir string, maps map[string][]CollabEntry) error {
	for agentName, entries := range maps {
		path := filepath.Join(agentsDir, agentName+".md")
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}

		updated := replaceCollabSection(string(content), renderCollabSection(entries))
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

const collabHeader = "## Collaboration Map"

// replaceCollabSection removes any existing Collaboration Map section and
// appends the new one. The section spans from `## Collaboration Map` to the
// next `## ` heading or EOF.
func replaceCollabSection(content, section string) string {
	lines := strings.Split(content, "\n")

	startIdx := -1
	endIdx := len(lines)

	for i, line := range lines {
		if strings.TrimSpace(line) == collabHeader {
			startIdx = i
			continue
		}
		if startIdx >= 0 && i > startIdx && strings.HasPrefix(line, "## ") {
			endIdx = i
			break
		}
	}

	if startIdx >= 0 {
		// Remove existing section
		kept := make([]string, 0, len(lines))
		kept = append(kept, lines[:startIdx]...)
		kept = append(kept, lines[endIdx:]...)
		lines = kept
	}

	// Trim trailing empty lines before appending
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}

	// Append new section with a blank line separator
	lines = append(lines, "", section)

	return strings.Join(lines, "\n")
}

// renderCollabSection generates the markdown for a collaboration map section.
func renderCollabSection(entries []CollabEntry) string {
	var b strings.Builder
	b.WriteString(collabHeader + "\n\n")
	b.WriteString("> Auto-generated by `ck agents registry --update`. Do not edit manually.\n\n")
	b.WriteString("| Agent | Direction | Shared Artifacts |\n")
	b.WriteString("|-------|-----------|------------------|\n")

	for _, e := range entries {
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", e.Agent, e.Direction, strings.Join(e.Artifacts, ", ")))
	}

	return b.String()
}
